
# Sample DNABot .ini file
# Read config.py for up to date info on what does what
# Strings can be quoted: this is not standard .ini syntax but I
# keep making that mistake so config.py will handle if present.

[DNABot]

#lifespan = 60
#backoff = 5
#heartbeat = 10

#results = "results.data"
#discovery = 0.01
#frankenstein = 0.001
#killBoost = 0.01

#chanAddr = "239.1.2.4"
##chanAddr = "ff05:0::ef:1:2:4"

#chanPort = 8421

#chanIface = ""

#PKT_SIZE = 1024

#QUEUE_SIZE = 512

#filePort = 8000
